### PR TITLE
Added User Agent entry to route request header. Fixes #16

### LINKED ISSUE #16: Calling calc_route_info() results in JSONDecodeError
Update: When looking deeper I noticed that the request in get_routes() returns a 403 error response.

Here's the error message at the bottom of the resulting stack trace:
```
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
This code should reproduce the error (confirmed on python 2.7):
```python
import WazeRouteCalculator


from_address = 'Los Angeles, CA'
to_address = 'San Fransisco, CA'
region = 'US'
route = WazeRouteCalculator.WazeRouteCalculator(from_address, to_address, region)
print route.calc_route_info()
```

### PR DESCRIPTION
**Pull request by gkhartman**
Adding a user agent to the request header seemed to fix the issue for me. Hard coded it for now but this might be something that should be moved to a config file later on. Confirmed by running the example.py found in the source code without any errors.

### CODE REVIEW

**Comment by kovacsbalu** [comment]
Hi, thanks for the fix. Can you please remove the unnecessary variable? Just add new header part to the dict. If you don't mind I can also change it.

**Comment by gkhartman** [comment]
@kovacsbalu I don't mind at all. I've made sure that edits to this pull request are enabled, so feel free to make changes.

**Comment by fabaff** [comment]
After this Pr is merged, can you please release a new package on PyPI. Thus, we can update the [dependency](https://github.com/home-assistant/home-assistant/issues/15157) in Home Assistant.

**Comment by kovacsbalu** [comment]
@fabaff definitely, I will notify you.

**Pull request merged**
