### PR TITLE
Request only a single path from Waze API

### PR DESCRIPTION
**Pull request by Scimonster**
No need to download multiple ones, it only takes extra time and bandwidth

### CODE REVIEW

**Comment by kovacsbalu** [comment]
What about `response_json['alternatives'][0]['response']`?

**Comment by Scimonster** [comment]
That's probably unnecessary now. Should i remove it?

**Comment by kovacsbalu** [comment]
Not exactly. Let's give a chance to generate alternative routes.

**Comment by Scimonster** [comment]
Is there anything else that needs to be done before this gets merged?

**Comment by kovacsbalu** [comment]
That's all :)

**Comment by Scimonster** [comment]
I didn't understand. Do you want me to remove the alternates code or leave it?

**Comment by kovacsbalu** [comment]
Leave it, and create a function to use alternative routes calc.

**Comment by Scimonster** [comment]
I'm confused why the alternative routes is needed. You just use the first
one, and it makes it slower. So what's it good for?

**Comment by kovacsbalu** [comment]
It is not needed but waze can handle it so why we drop out?

**Comment by Scimonster** [comment]
If this was a simple waze API client, I would agree. But it isn't (at the
moment); it's a service for estimating travel time and distance. So you
would end up with two methods that return the same result, but one is three
times slower.

**Comment by kovacsbalu** [comment]
Yes, now I know it and also thanks for your fix!
I will create another func for alt routes. Is it ok for you?

**Comment by Scimonster** [comment]
I still think it's unnecessary, but it is your project, so in the end it's
your choice.

**Comment by Scimonster** [comment]
I think if you're going to keep the method that fetches three routes, it should at least give you the data for all three:

`r.calc_all_routes_info() == [(t1, d1), (t2, d2), (t3, d3)]`

(Should always return an array, even if there's only one route.)

**Comment by kovacsbalu** [comment]
what is t1, d1...?

**Comment by Scimonster** [comment]
time for route 1, distance for route 1, etc

**Comment by kovacsbalu** [comment]
Looks, good. probably need to configure rout numbers in _init_

**Comment by Scimonster** [comment]
Or as a parameter to `calc_route_info`.

**Comment by Scimonster** [comment]
I'm going to work on the `calc_all_routes_info` and send a new PR.

**Comment by Scimonster** [comment]
PR replaced with #10.

**Pull request closed without merging**
