### PR TITLE
Need explicit route option whatever it is false or true

### PR DESCRIPTION
**Pull request by Chrominator**
Hi,
I've noticed that Waze has probably changed something, distance and lasting of a route is the same whatever we use toll roads or not.
It seems that if we do not use the explicit option AVOID_TOLL_ROADS with False, it revert to AVOID_TOLL_ROADS with True.

### CODE REVIEW

**Comment by kovacsbalu** [comment]
Hi @Chrominator, thanks for your PR!
Can you please fix tests also?
Btw there is not much information in the examples so please remove them.

**Comment by Chrominator** [comment]
Done

**Comment by kovacsbalu** [comment]
Where? :)

**Comment by Chrominator** [comment]
Ok, I'll dig into the tests and will tell you once it's done

**Pull request closed without merging**
