### PR TITLE
added time_delta and headers to request

### PR DESCRIPTION
**Pull request by lovato**
This fixes the problem from last days about Waze requesting some headers on the GET, and additionally, I made possible to query Waze for different hours of the day ("at" parameter).

### CODE REVIEW

**Comment by lovato** [comment]
Please, if accepting, bump the version.

**Comment by kovacsbalu** [comment]
Looks, good. Thanks!

**Comment by randyinla** [comment]
I realize I'm over a year late to the conversation... but how do you actually use the time_delta?  Is it a date/time object?  An integer?  12h or 24h based?  Minutes from "now"?  The main readme doesn't even mention it was merged into master.  I've tried a few different things with zero success.  Comparing against the actual Waze app on my iPhone to see if the returned time is correct for 6 hours from "now".

**Comment by kovacsbalu** [comment]
Hi @randyinla, good question thanks! :)
I also checked live map and routing params and got this.
At 09.54 set leave at to 10.00 and "at" param got 6.
At 10.01 set leave at to 10.00 and "at" param got 1439.
So "at" between 0 and 1440. 0 mean now, 600 mean now + 600 minute.
I will update docs with this info!

**Pull request merged**
