### PR TITLE
Change to allow gps coordinates as to or from address

### PR DESCRIPTION
**Pull request by bjohnson8949**
Actual code changes allow the use of gps coordinates as to and from address.

Added:
- already_coords
- coords_string_parser

Made changes to init to decide if to \ from address is actually gps coordinates.

### CODE REVIEW

**Comment by kovacsbalu** [comment]
Hi @bjohnson8949 good feature, but can you please commit some test for this new functions?

**Comment by SConaway** [comment]
Can we please merge this as-is? The address to coords is kinda broken where I live and would like to use an official release.

**Comment by kovacsbalu** [comment]
Hi @SConaway, as I mentioned yes this is a good feature. I will do some refact and test before merge.
Coming soon :)

**Comment by hmmbob** [comment]
Hello @kovacsbalu,

Your package is being used in [Home Assistant](https://github.com/home-assistant/home-assistant), an open source smart home software platform. Thank you for your work on this package, as it enables a lot of users to use Waze for travel time calculations. The Home Assistant "Waze Travel Time Sensor" displays the time needed to travel from one point to another, quite often from a device trackers current location to the 'home' or 'work' zone. Home Assistant uses coordinates for "zones" (e.g. 'home','work') and for the location of device-trackers, instead of addresses. 

Home Assistant currently uses version 0.6 of your package. Several users (including myself) have issues with unhandled errors with this package, which seem to have been [solved by you in later versions](https://github.com/kovacsbalu/WazeRouteCalculator/commit/a419099ce67e8fed0bebd888ead7082ff4d9ef20). However, if we use the most recent version, we cannot pass coordinates to your package anymore. For whatever reason, this worked fine in 0.6, but no longer in 0.7.2. As said, Home Assistant uses coordinates for "zones" (e.g. 'home','work') and for the location of device-trackers. 

Would it be possible to merge this functionality into your package, so we can update the package requirements for Home Assistant? I would gladly help, if I only knew some decent Python. I don't, hence my plea for your help.

Above all, thank you for providing this package to the community.

**Comment by kovacsbalu** [comment]
Hi @hmmbob, thanks for your details. I'm already a HA user :) 
Maybe `if response_json.get('city'):` cause this problem. I will fix it and create version 0.8 with coord support.

**Comment by hmmbob** [comment]
Awesome! I didn't know you're using HA too - good to hear! Does that mean that whenever 0.8 gets released, you will also update the waze travel sensor in HA itself?

Thanks again - I don't want to be a guy "requiring support" or so and would gladly have done it myself, but I don't speak Python....

**Comment by kovacsbalu** [comment]
@hmmbob, @bjohnson8949 can you please check tag '0.8' before releasing?

**Comment by hmmbob** [comment]
Sure, give me a few minutes

Op za 16 feb. 2019 om 15:34 schreef Kovács Bálint <notifications@github.com

**Comment by kovacsbalu** [comment]
@hmmbob maybe...but I never tried HA  waze sensor :D

**Comment by hmmbob** [comment]
Ok, I have 3 sensors set up in Home Assistant:

1) my location -> home
2) home -> work
3) work -> home

All are coordinate based. 2 & 3 loaded fine upon home assistant start; 1) gave an error:

```2019-02-16 15:42:02 ERROR (SyncWorker_3) [custom_components.sensor.waze_travel_time] Error on retrieving data: empty response```

However, waiting 5 minutes (which is the default scan interval of the Home Assistant Waze sensor) did update my sensor quite fine.

So, besides raising an error because of an empty response from the server, all is working fine now!

**Comment by kovacsbalu** [comment]
Released... :)
BTW, some times I also got `empty response` with caused by `429 Too Many Requests`

**Comment by hmmbob** [comment]
Thanks, I will pull it into HA!

**Comment by SConaway** [comment]
What format for lat/long does it take?

**Comment by hmmbob** [comment]
This is a mock coordinate for one of my device trackers that works:  51.12345, 5.123456

**Comment by SConaway** [comment]
It works for some lat/lons, but not all.

Steven

**Comment by kovacsbalu** [comment]
@SConaway format is `lat, lon = coords.split(',')`

**Pull request merged**
